/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatos.UI;
import basedatos.Clases.BancoClass;
import basedatos.Clases.CategoriaAcademicaClass;
import basedatos.Clases.EstadoCivilClass;
import basedatos.Clases.GrupoSanguineoClass;
import basedatos.Clases.NivelEducativoClass;
import basedatos.Clases.OcupacionClass;
import basedatos.Clases.PaisClass;
import basedatos.Clases.RegimenClass;
import basedatos.Clases.RegimenPensionarioClass;
import basedatos.Clases.SedeClass;
import basedatos.Clases.SexoClass;
import basedatos.Clases.SinoClass;
import basedatos.Clases.SituacionEPSClass;
import basedatos.Clases.TipoContratoClass;
import basedatos.Clases.TipoDocumentoClass;
import basedatos.Clases.TipoRegimenClass;
import basedatos.Clases.TipoTrabajorClass;
import basedatos.Clases.UbigeoClass;
import basedatos.Conexion;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marie
 */
public class Personal extends javax.swing.JFrame {
    
    char flag = '_';
    ArrayList<TipoDocumentoClass> tipoDocumento;
    ArrayList<RegimenPensionarioClass> regimenPensionario;
    ArrayList<OcupacionClass> ocupacion;
    ArrayList<UbigeoClass> ubigeo;
    ArrayList<PaisClass> pais;
    ArrayList<BancoClass> banco;
    ArrayList<NivelEducativoClass> nivelEducativo;
    ArrayList<SituacionEPSClass> situacionEPS;
    ArrayList<SexoClass> sexo;
    ArrayList<GrupoSanguineoClass> grupoSanguineo;
    ArrayList<EstadoCivilClass> estadoCivil;
    ArrayList<SinoClass> sino;

    /**
     * Creates new form Personal
     */
    public Personal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        materno = new javax.swing.JTextField();
        paterno = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        documento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        paternoConyuge = new javax.swing.JTextField();
        maternoConyuge = new javax.swing.JTextField();
        nombreConyuge = new javax.swing.JTextField();
        numeroHijos = new javax.swing.JSpinner();
        otrosIngresos = new javax.swing.JTextField();
        numeroCuenta = new javax.swing.JTextField();
        dia = new javax.swing.JSpinner();
        mes = new javax.swing.JSpinner();
        anio = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        comboBox_banco = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        comboBox_nivelEducativoDes = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        comboBox_ocupacion = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        comboBox_SituacionEPS = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        comboBox_Sexo = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        comboBox_GrupoSanguineo = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        comboBox_EstadoCivil = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        comboBox_pais = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox20 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        comboBox_tipoDocumento = new javax.swing.JComboBox<>();
        jButton16 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        comboBox_ubigeo = new javax.swing.JComboBox<>();
        jButton22 = new javax.swing.JButton();
        comboBox_Regimen = new javax.swing.JComboBox<>();
        comboBox_Discapacidad = new javax.swing.JComboBox<>();
        comboBox_Sindicalizado = new javax.swing.JComboBox<>();
        comboBox_ControlInmediato = new javax.swing.JComboBox<>();
        jButton25 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        comboBox_Seguro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Apellido paterno");

        jLabel2.setText("Apellido materno");

        jLabel3.setText("Nombre trabajor");

        jLabel4.setText("Numero de documento");

        jLabel5.setText("Fecha de nacimiento");

        jLabel6.setText("Domicilio");

        jLabel7.setText("Correo electronico");

        jLabel8.setText("Telefono");

        jLabel9.setText("Celular");

        jLabel10.setText("Apellido paterno conyuge");

        jLabel11.setText("Apellido materno conyuge");

        jLabel12.setText("Nombre conyuge");

        jLabel13.setText("Numero hijos");

        jLabel14.setText("Otros ingresos");

        jLabel15.setText("Numero de cuenta");

        jLabel17.setText("dia: ");

        jLabel18.setText("mes: ");

        jLabel19.setText("ano: ");

        numeroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroCuentaActionPerformed(evt);
            }
        });

        dia.setVerifyInputWhenFocusTarget(false);

        jLabel20.setText("Ubigeo");

        comboBox_banco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco de la Nacion", "Interbank" }));

        jLabel21.setText("Nivel educativo");

        comboBox_nivelEducativoDes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primaria", "Secundaria", "Tecnico", "Universitario" }));

        jLabel22.setText("Ocupacion");

        comboBox_ocupacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor", "No Especifica" }));

        jLabel23.setText("Regimen pensionario");

        jLabel24.setText("Situacion EPS");

        comboBox_SituacionEPS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Activo" }));
        comboBox_SituacionEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_SituacionEPSActionPerformed(evt);
            }
        });

        jLabel25.setText("Sexo");

        comboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel26.setText("Grupo Sanguineo");

        comboBox_GrupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPositivo", "ONegativo", "APositivo", "ANegativo", "BPositivo", "BNgativo", "ABPositivo", "ABNegativo" }));

        jLabel27.setText("Descapacidad");

        jLabel28.setText("Estado civil");

        comboBox_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero(a)", "Casado(a)", "Viudo(a)", "Divorciado(a)", "Conviviente" }));

        jLabel31.setText("Sindicalizado");

        comboBox_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peru", "Chile", "Mexico" }));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel33.setText("Control inmediato");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I", "*" }));

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");

        jButton4.setText("Cancelar");

        jButton5.setText("Inactivar");

        jButton6.setText("Reactivar");

        jButton7.setText("Actualizar");

        jButton8.setText("Salir");

        jLabel16.setText("Codigo");

        jLabel35.setText("Estado registro");

        jButton11.setText("Modificar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton14.setText("Modificar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        comboBox_tipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton16.setText("Actualizar Grillas");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton12.setText("Modificar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Modificar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setText("Modificar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton17.setText("Modificar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Modificar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Modificar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel34.setText("Pais");

        jButton21.setText("Modificar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        comboBox_ubigeo.setEditable(true);
        comboBox_ubigeo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton22.setText("Modificar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        comboBox_Regimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBox_Discapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBox_Sindicalizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBox_ControlInmediato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton25.setText("Modificar");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jLabel32.setText("Seguro");

        comboBox_Seguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox_tipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel33))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBox_Regimen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboBox_ControlInmediato, javax.swing.GroupLayout.Alignment.LEADING, 0, 88, Short.MAX_VALUE)
                                        .addComponent(comboBox_Discapacidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBox_Sindicalizado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBox_Seguro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(maternoConyuge)
                                        .addComponent(nombre)
                                        .addComponent(materno)
                                        .addComponent(paterno)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(48, 48, 48)
                                            .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(codigo)
                                        .addComponent(nombreConyuge, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(paternoConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numeroHijos, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBox_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(domicilio))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel35))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(celular)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBox_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(otrosIngresos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBox20, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBox_EstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBox_GrupoSanguineo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBox_SituacionEPS, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBox_Sexo, javax.swing.GroupLayout.Alignment.LEADING, 0, 233, Short.MAX_VALUE)
                                            .addComponent(comboBox_nivelEducativoDes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefono)
                                    .addComponent(correo)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel20))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(comboBox_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(comboBox_ubigeo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(comboBox_ubigeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton22))
                            .addGap(7, 7, 7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(comboBox_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(otrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(numeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBox_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(comboBox_nivelEducativoDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(comboBox_SituacionEPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(comboBox_Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(comboBox_GrupoSanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(comboBox_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11)
                            .addComponent(comboBox_tipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(paternoConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(maternoConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nombreConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(numeroHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(comboBox_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(comboBox_Regimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(comboBox_Discapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(comboBox_Sindicalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(comboBox_ControlInmediato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(comboBox_Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)))
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBox_SituacionEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_SituacionEPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_SituacionEPSActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        TipoDocumento tipoDocumento = new TipoDocumento();
        tipoDocumento.setTitle("Tipo de Documento");
        try {
        String sql = "SELECT * FROM tipo_documento";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("TipDocCod");
            String e = rs.getString("TipDocDes");
            String f = rs.getString("TipDocEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        tipoDocumento.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
        tipoDocumento.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Ocupacion ocupacion = new Ocupacion();
        ocupacion.setTitle("Ocupacion");
        try {
        String sql = "SELECT * FROM ocupacion";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("OcuCod");
            String e = rs.getString("OcuDes");
            String f = rs.getString("OcuEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        ocupacion.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        ocupacion.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
    }//GEN-LAST:event_jButton16ActionPerformed

    private void numeroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroCuentaActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Ubigeo ubigeo = new Ubigeo();
        ubigeo.setTitle("Ubigeo");
        try {
        String sql = "SELECT * FROM ubigeo";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Departamento","Provincia","Distrito", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("UbiCod");
            String e = rs.getString("UbiDep");
            String f = rs.getString("UbiPro");
            String g = rs.getString("UbiDis");
            String h = rs.getString("UbiEstReg");
            model.addRow(new Object[]{d, e, f, g, h });
        }
        ubigeo.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        ubigeo.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Pais pais = new Pais();
        pais.setTitle("Pais");
        try {
        String sql = "SELECT * FROM pais";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("PaiCod");
            String e = rs.getString("PaiDes");
            String f = rs.getString("PaiEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        pais.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        pais.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Banco banco = new Banco();
        banco.setTitle("Banco");
        try {
        String sql = "SELECT * FROM banco";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("BanCod");
            String e = rs.getString("BanNom");
            String f = rs.getString("BanEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        banco.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Banco.class.getName()).log(Level.SEVERE, null, ex);
        }
        banco.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        NivelEducativo nivelEducativo = new NivelEducativo();
        nivelEducativo.setTitle("Nivel educativo");
        try {
        String sql = "SELECT * FROM nivel_educativo";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion","Nivel grado", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("NivEduCod");
            String e = rs.getString("NivEduDes");
            String f = rs.getString("NivEduNivGra");
            String g = rs.getString("NivEduEstReg");;
            model.addRow(new Object[]{d, e, f, g});
        }
        nivelEducativo.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(NivelEducativo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(NivelEducativo.class.getName()).log(Level.SEVERE, null, ex);
        }
        nivelEducativo.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        SituacionEps situacionEps = new SituacionEps();
        situacionEps.setTitle("Situacion EPS");
        try {
        String sql = "SELECT * FROM situacion_eps";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("SitEpsCod");
            String e = rs.getString("SitEpsDes");
            String f = rs.getString("SitEpsEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        situacionEps.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        situacionEps.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        Sexo sexo = new Sexo();
        sexo.setTitle("Sexo");
        try {
        String sql = "SELECT * FROM sexo";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("SexCod");
            String e = rs.getString("SexDes");
            String f = rs.getString("SexEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        sexo.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        sexo.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        GrupoSanguineo grupoSanguineo = new GrupoSanguineo();
        grupoSanguineo.setTitle("Grupo Sanguineo");
        try {
        String sql = "SELECT * FROM grupo_sanguineo";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("GruSanCod");
            String e = rs.getString("GruSanDes");
            String f = rs.getString("GruSanEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        grupoSanguineo.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(GrupoSanguineo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(GrupoSanguineo.class.getName()).log(Level.SEVERE, null, ex);
        }
        grupoSanguineo.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        EstadoCivil estadoCivil = new EstadoCivil();
        estadoCivil.setTitle("Estado Civil");
        try {
        String sql = "SELECT * FROM estado_civil";
        Statement s = Conexion.obtener().createStatement();
        ResultSet rs = s.executeQuery(sql);
        DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Estado de registro"}, 0);
        while(rs.next())
        {
            String d = rs.getString("EstCivCod");
            String e = rs.getString("EstCivDes");
            String f = rs.getString("EstCivEstReg");
            model.addRow(new Object[]{d, e, f });
        }
        estadoCivil.getJTable().setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(EstadoCivil.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(EstadoCivil.class.getName()).log(Level.SEVERE, null, ex);
        }
        estadoCivil.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PreparedStatement ps = Conexion.obtener().prepareStatement("START TRANSACTION;");
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }

        switch(flag)
        {
            case 'm':
            try {
                Statement s = Conexion.obtener().createStatement();
                //PreparedStatement ps = Conexion.obtener().prepareStatement("UPDATE `tipo_regimen_pensionario`"
                //    + "SET `afp_AfpCod` = '"+ codigoafp.getText() +"', `TipRegPenDes` = '"
                //    + descripcion.getText()+"', `TipRegPenEstReg` = '"+ estado.getText() +"'"
                //    + "WHERE `tipo_regimen_pensionario`.`TipRegPenCod` = '"+ codigo.getText() +"'; ");
                //ps.execute();
                //ps = Conexion.obtener().prepareStatement("COMMIT;");
                //ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case 'e':
            try {
                Statement s = Conexion.obtener().createStatement();
                //PreparedStatement ps = Conexion.obtener().prepareStatement("UPDATE `tipo_regimen_pensionario`"
                //    + "SET `TipRegPenEstReg` = '*' "
                //    + "WHERE `tipo_regimen_pensionario`.`TipRegPenCod` = '"+ codigo.getText() +"'; ");
                //ps.execute();
                //ps = Conexion.obtener().prepareStatement("COMMIT;");
                //ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case 'i':
            try {
                Statement s = Conexion.obtener().createStatement();
                //PreparedStatement ps = Conexion.obtener().prepareStatement("UPDATE `tipo_regimen_pensionarioo`"
                //    + "SET `TipRegPenEstReg` = 'I' "
                //    + "WHERE `tipo_regimen_pensionario`.`TipRegPenCod` = '"+ codigo.getText() +"'; ");
                //ps.execute();
                //ps = Conexion.obtener().prepareStatement("COMMIT;");
                //ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case 'r':
            try {
                Statement s = Conexion.obtener().createStatement();
                //PreparedStatement ps = Conexion.obtener().prepareStatement("UPDATE `tipo_regimen_pensionario`"
                //    + "SET `TipRegPenEstReg` = 'A'"
                //    + "WHERE `tipo_regimen_pensionario`.`TipRegPenCod` = '"+ codigo.getText() +"'; ");
                //ps.execute();
                //ps = Conexion.obtener().prepareStatement("COMMIT;");
                //ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case 'a':
            try {
                //Buscar codigo
                String selecTipoDocumento = "000000";
                for (TipoDocumentoClass tipoDocumentoClass : tipoDocumento) {
                    if (tipoDocumentoClass.getTipDocDes().equals(comboBox_tipoDocumento.getSelectedItem().toString()))
                        selecTipoDocumento = tipoDocumentoClass.getTipDocCod();
                }
                String selecOcupacion = "000000";
                for (OcupacionClass ocupacion : ocupacion) {
                    if (ocupacion.getOcuDes().equals(comboBox_ocupacion.getSelectedItem().toString()))
                        selecOcupacion = ocupacion.getOcuCod();
                }
                String selecRegimenPensionario = "000000";
                for (RegimenPensionarioClass regimenPensionario : regimenPensionario) {
                    if (regimenPensionario.getRegPenCod().equals(comboBox_ocupacion.getSelectedItem().toString()))
                        selecRegimenPensionario = regimenPensionario.getRegPenCod();
                }
                String selecPais = "000000";
                for (PaisClass pais : pais) {
                    if (pais.getPaiDes().equals(comboBox_pais.getSelectedItem().toString()))
                        selecPais = pais.getPaiCod();
                }
                String selecBanco = "000000";
                for (BancoClass banco : banco) {
                    if (banco.getBanNom().equals(comboBox_banco.getSelectedItem().toString()))
                        selecBanco = banco.getBanCod();
                }
                String selecNivelEducativo = "000000";
                for (NivelEducativoClass nivelEducativo : nivelEducativo) {
                    if (nivelEducativo.getNivEduDes().equals(comboBox_nivelEducativoDes.getSelectedItem().toString()))
                        selecNivelEducativo = nivelEducativo.getNivEduCod();
                }
                String selecSituacionEPS = "000000";
                for (SituacionEPSClass situacionEPS : situacionEPS) {
                    if (situacionEPS.getSitEpsDes().equals(comboBox_SituacionEPS.getSelectedItem().toString()))
                        selecSituacionEPS = situacionEPS.getSitEpsCod();
                }
                String selecSexo = "000000";
                for (SexoClass sexo : sexo) {
                    if (sexo.getSexDes().equals(comboBox_Sexo.getSelectedItem().toString()))
                        selecSexo = sexo.getSexCod();
                }
                String selecGrupoSanguineo = "000000";
                for (GrupoSanguineoClass grupoSanguineo : grupoSanguineo) {
                    if (grupoSanguineo.getGruSanDes().equals(comboBox_GrupoSanguineo.getSelectedItem().toString()))
                        selecGrupoSanguineo = grupoSanguineo.getGruSanCod();
                }
                String selecEstadoCivil = "000000";
                for (EstadoCivilClass estadoCivil : estadoCivil) {
                    if (estadoCivil.getEstCivDes().equals(comboBox_EstadoCivil.getSelectedItem().toString()))
                        selecEstadoCivil = estadoCivil.getEstCivCod();
                }
                String selecDiscapacidad = "0";
                for (SinoClass sino : sino) {
                    if (sino.getSinDes().equals(comboBox_Discapacidad.getSelectedItem().toString()))
                        selecDiscapacidad = sino.getSinCod();
                }
                String selecControlInmediato = "0";
                for (SinoClass sino : sino) {
                    if (sino.getSinDes().equals(comboBox_ControlInmediato.getSelectedItem().toString()))
                        selecControlInmediato = sino.getSinCod();
                }
                String selecSindicalizado = "0";
                for (SinoClass sino : sino) {
                    if (sino.getSinDes().equals(comboBox_Sindicalizado.getSelectedItem().toString()))
                        selecSindicalizado = sino.getSinCod();
                }
                String selecSeguro = "0";
                for (SinoClass sino : sino) {
                    if (sino.getSinDes().equals(comboBox_Seguro.getSelectedItem().toString()))
                        selecSeguro = sino.getSinCod();
                }
                
                Statement s = Conexion.obtener().createStatement();
                PreparedStatement ps = Conexion.obtener().prepareStatement("INSERT INTO `personal` "
                        + "(`PerCod`, `PerApePat`, `PerApeMat`, `PerTraNom`, `PerDocNum`, `PerFecNacAnio`, "
                        + "`PerFecNacMes`, `PerFecNacDia`, `PerDom`, `PerCorEle`, `PerTel`, `PerCel`, "
                        + "`PerConApePat`, `PerConApeMat`, `PerConNom`, `PerHijNum`, `PerOtrIng`, "
                        + "`PerCueNum`, `PerEstReg`, `OCUPACION_OcuCod`, `REGIMEN_PENSIONARIO_RegPenCod`, "
                        + "`BANCO_BanCod1`, `SITUACION_EPS_SitEpsCod`, `PAIS_PaiCod`, `UBIGEO_UbiCod`, "
                        + "`ESTADO_CIVIL_EstCivCod`, `GRUPO_SANGUINEO_GruSanCod`, `NIVEL_EDUCATIVO_NivEduCod`, "
                        + "`SEXO_SexCod`, `TIPO_DOCUMENTO_TipDocCod`, `PerDisCod`, `PerSinCod`, "
                        + "`PerSegCod`, `PerConInmCod`) VALUES "
                        + "('"+codigo.getText()+"', '"+paterno.getText()+"', '"+materno.getText()+"', "
                        + "'"+nombre.getText()+"', '"+documento.getText()+"', '"+anio.getValue()+"', "
                        + "'"+mes.getValue()+"', '"+dia.getValue()+"', '"+domicilio.getText()+"', "
                        + "'"+correo.getText()+"', '"+telefono.getText()+"', '"+celular.getText()+"', "
                        + "'"+paternoConyuge.getText()+"', '"+maternoConyuge.getText()+"', '"+nombreConyuge.getText()+"', "
                        + "'"+numeroHijos.getValue()+"', '"+otrosIngresos.getText()+"', '"+numeroCuenta.getText()+"', "
                        + "'"+jComboBox20.getSelectedItem().toString()+"', '"++"', '"++"', "
                        + "'"++"', '"++"', '"++"', "
                        + "'"++"', '"++"', '"++"', "
                        + "'"++"', '"++"', '"++"', "
                        + "'"++"', '"++"', '"++"', '"++"');");
                ps.execute();
                ps = Conexion.obtener().prepareStatement("COMMIT;");
                ps.execute();
            } catch (SQLException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            default:
        }
        try {
            String sql = "SELECT * FROM regimen_pensionario";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "SPP CUS","ANO", "MES", "DIA", "Estado", "Tipo"}, 0);
            while(rs.next())
            {
                String d = rs.getString("RegPenCod");
                String e = rs.getString("RegPenSppCus");
                String f = rs.getString("RegPenFecInsAnio");
                String g = rs.getString("RegPenFecInsMes");
                String h = rs.getString("RegPenFecInsDia");
                String i = rs.getString("RegPenEstReg");
                String j = rs.getString("TIPO_REGIMEN_PENSIONARIO_TipRegPenCod");
                model.addRow(new Object[]{d, e, f, g, h, i, j});
            }
            jTable2.setModel(model);
            //codigo.setText("");
            
            //spp_cuspp.setText("");
            //estado.setSelectedIndex(-1);
        } catch (SQLException ex) {
            Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TipoTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }

        flag = '_';
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        RegimenPensionario regimenPensionario = new RegimenPensionario();
        regimenPensionario.setTitle("Regimen Pensionario");
        try {
            String sql = "SELECT * FROM regimen_pensionario";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "SPP CUS","ANO", "MES", "DIA", "Estado", "Tipo"}, 0);
            while(rs.next())
            {
                String d = rs.getString("RegPenCod");
                String e = rs.getString("RegPenSppCus");
                String f = rs.getString("RegPenFecInsAnio");
                String g = rs.getString("RegPenFecInsMes");
                String h = rs.getString("RegPenFecInsDia");
                String i = rs.getString("RegPenEstReg");
                String j = rs.getString("TIPO_REGIMEN_PENSIONARIO_TipRegPenCod");
                model.addRow(new Object[]{d, e, f, g, h, i, j});
            }
            regimenPensionario.getJTable().setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(NivelEducativo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(NivelEducativo.class.getName()).log(Level.SEVERE, null, ex);
        }
        regimenPensionario.comboBox_TipoRegimen();
        regimenPensionario.setVisible(true);
    }//GEN-LAST:event_jButton25ActionPerformed

    public void comboBox_Sino() {
        try {
            sino = new ArrayList<SinoClass>();
            String sql = "SELECT * FROM sino";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("SinEstReg").equals("A")) {
                    sino.add(new SinoClass(
                            rs.getString("SinCod"),
                            rs.getString("SinDes"),
                            rs.getString("SinEstReg")));
                }
            }
            String [] arrSino = new String [sino.size()];
            for (int i = 0; i < arrSino.length; i++) {
                arrSino[i] = sino.get(i).getSinDes();
            }
            comboBox_Discapacidad.setModel(new javax.swing.DefaultComboBoxModel(arrSino));
            comboBox_ControlInmediato.setModel(new javax.swing.DefaultComboBoxModel(arrSino));
            comboBox_Sindicalizado.setModel(new javax.swing.DefaultComboBoxModel(arrSino));
            comboBox_Seguro.setModel(new javax.swing.DefaultComboBoxModel(arrSino));
        } catch (SQLException ex) {
            Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_EstadoCivil() {
        try {
            estadoCivil = new ArrayList<EstadoCivilClass>();
            String sql = "SELECT * FROM estado_civil";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("EstCivEstReg").equals("A")) {
                    estadoCivil.add(new EstadoCivilClass(
                            rs.getString("EstCivCod"),
                            rs.getString("EstCivDes"),
                            rs.getString("EstCivEstReg")));
                }
            }
            String [] arrEstadoCivil = new String [estadoCivil.size()];
            for (int i = 0; i < arrEstadoCivil.length; i++) {
                arrEstadoCivil[i] = estadoCivil.get(i).getEstCivDes();
            }
            comboBox_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(arrEstadoCivil));;
        } catch (SQLException ex) {
            Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_GrupoSanguineo() {
        try {
            grupoSanguineo = new ArrayList<GrupoSanguineoClass>();
            String sql = "SELECT * FROM grupo_sanguineo";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("GruSanEstReg").equals("A")) {
                    grupoSanguineo.add(new GrupoSanguineoClass(
                            rs.getString("GruSanCod"),
                            rs.getString("GruSanDes"),
                            rs.getString("GruSanEstReg")));
                }
            }
            String [] arrGrupoSanguineo = new String [grupoSanguineo.size()];
            for (int i = 0; i < arrGrupoSanguineo.length; i++) {
                arrGrupoSanguineo[i] = grupoSanguineo.get(i).getGruSanDes();
            }
            comboBox_GrupoSanguineo.setModel(new javax.swing.DefaultComboBoxModel(arrGrupoSanguineo));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_Sexo() {
        try {
            sexo = new ArrayList<SexoClass>();
            String sql = "SELECT * FROM sexo";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("SexEstReg").equals("A")) {
                    sexo.add(new SexoClass(
                            rs.getString("SexCod"),
                            rs.getString("SexDes"),
                            rs.getString("SexEstReg")));
                }
            }
            String [] arrSexo = new String [sexo.size()];
            for (int i = 0; i < arrSexo.length; i++) {
                arrSexo[i] = sexo.get(i).getSexDes();
            }
            comboBox_Sexo.setModel(new javax.swing.DefaultComboBoxModel(arrSexo));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_SituacionEPS() {
        try {
            situacionEPS = new ArrayList<SituacionEPSClass>();
            String sql = "SELECT * FROM situacion_eps";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("SitEpsEstReg").equals("A")) {
                    situacionEPS.add(new SituacionEPSClass(
                            rs.getString("SitEpsCod"),
                            rs.getString("SitEpsDes"),
                            rs.getString("SitEpsEstReg")));
                }
            }
            String [] arrSituacionEPS = new String [situacionEPS.size()];
            for (int i = 0; i < arrSituacionEPS.length; i++) {
                arrSituacionEPS[i] = situacionEPS.get(i).getSitEpsDes();
            }
            comboBox_SituacionEPS.setModel(new javax.swing.DefaultComboBoxModel(arrSituacionEPS));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_nivelEducativoDes() {
        try {
            nivelEducativo = new ArrayList<NivelEducativoClass>();
            String sql = "SELECT * FROM nivel_educativo";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("NivEduEstReg").equals("A")) {
                    nivelEducativo.add(new NivelEducativoClass(
                            rs.getString("NivEduCod"),
                            rs.getString("NivEduDes"),
                            rs.getString("NivEduNivGra"),
                            rs.getString("NivEduEstReg")));
                }
            }
            String [] arrNivelEducativo = new String [nivelEducativo.size()];
            for (int i = 0; i < arrNivelEducativo.length; i++) {
                arrNivelEducativo[i] = nivelEducativo.get(i).getNivEduDes();
            }
            comboBox_nivelEducativoDes.setModel(new javax.swing.DefaultComboBoxModel(arrNivelEducativo));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_banco() {
        try {
            banco = new ArrayList<BancoClass>();
            String sql = "SELECT * FROM banco";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("BanEstReg").equals("A")) {
                    banco.add(new BancoClass(
                            rs.getString("BanCod"),
                            rs.getString("BanNom"),
                            rs.getString("BanEstReg")));
                }
            }
            String [] arrBanco = new String [banco.size()];
            for (int i = 0; i < arrBanco.length; i++) {
                arrBanco[i] = banco.get(i).getBanNom();
            }
            comboBox_banco.setModel(new javax.swing.DefaultComboBoxModel(arrBanco));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_pais() {
        try {
            pais = new ArrayList<PaisClass>();
            String sql = "SELECT * FROM pais";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("PaiEstReg").equals("A")) {
                    pais.add(new PaisClass(
                            rs.getString("PaiCod"),
                            rs.getString("PaiDes"),
                            rs.getString("PaiEstReg")));
                }
            }
            String [] arrPais = new String [pais.size()];
            for (int i = 0; i < arrPais.length; i++) {
                arrPais[i] = pais.get(i).getPaiDes();
            }
            comboBox_pais.setModel(new javax.swing.DefaultComboBoxModel(arrPais));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_ubigeo() {
        try {
            ubigeo = new ArrayList<UbigeoClass>();
            String sql = "SELECT * FROM ubigeo";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("UbiEstReg").equals("A")) {
                    ubigeo.add(new UbigeoClass(
                            rs.getString("UbiCod"),
                            rs.getString("UbiDep"),
                            rs.getString("UbiPro"),
                            rs.getString("UbiDis"),
                            rs.getString("UbiEstReg")));
                }
            }
            String [] arrUbigeo = new String [ubigeo.size()];
            for (int i = 0; i < arrUbigeo.length; i++) {
                arrUbigeo[i] = ubigeo.get(i).getUbiCod();
            }
            comboBox_ubigeo.setModel(new javax.swing.DefaultComboBoxModel(arrUbigeo));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    public void comboBox_ocupacion() {
        try {
            ocupacion = new ArrayList<OcupacionClass>();
            String sql = "SELECT * FROM ocupacion";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("OcuEstReg").equals("A")) {
                    ocupacion.add(new OcupacionClass(rs.getString("OcuCod"),
                            rs.getString("OcuDes"),
                            rs.getString("OcuEstReg")));
                }
            }
            String [] arrOcupacion = new String [ocupacion.size()];
            for (int i = 0; i < arrOcupacion.length; i++) {
                arrOcupacion[i] = ocupacion.get(i).getOcuDes();
            }
            comboBox_ocupacion.setModel(new javax.swing.DefaultComboBoxModel(arrOcupacion));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void comboBox_Regimen() {
        try {
            regimenPensionario = new ArrayList<RegimenPensionarioClass>();
            String sql = "SELECT * FROM regimen_pensionario";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("RegPenEstReg").equals("A")) {
                    regimenPensionario.add(new RegimenPensionarioClass(rs.getString("RegPenCod"),
                            rs.getString("RegPenSppCus"),
                            rs.getString("RegPenFecInsAnio"),
                            rs.getString("RegPenFecInsMes"),
                            rs.getString("RegPenFecInsDia"),
                            rs.getString("RegPenEstReg"),
                            rs.getString("TIPO_REGIMEN_PENSIONARIO_TipRegPenCod")));
                }
            }
            String [] arrRegimenPensionario = new String [regimenPensionario.size()];
            for (int i = 0; i < arrRegimenPensionario.length; i++) {
                arrRegimenPensionario[i] = regimenPensionario.get(i).getRegPenCod();
            }
            comboBox_Regimen.setModel(new javax.swing.DefaultComboBoxModel(arrRegimenPensionario));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void comboBox_tipoDocumento() {
        try {
            tipoDocumento = new ArrayList<TipoDocumentoClass>();
            String sql = "SELECT * FROM tipo_documento";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            while(rs.next())
            {
                if (rs.getString("TipDocEstReg").equals("A")) {
                    tipoDocumento.add(new TipoDocumentoClass(rs.getString("TipDocCod"), rs.getString("TipDocDes"),
                            rs.getString("TipDocEstReg")));
                }
            }
            String [] arrtipoDocumento = new String [tipoDocumento.size()];
            for (int i = 0; i < arrtipoDocumento.length; i++) {
                arrtipoDocumento[i] = tipoDocumento.get(i).getTipDocDes();
            }
            comboBox_tipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(arrtipoDocumento));;
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public JTable getJTable () {
        return jTable2;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Personal personal = new Personal();
        personal.setVisible(true);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        personal.setLocation(dim.width/2-personal.getSize().width/2, dim.height/2-personal.getSize().height/2);
        personal.setTitle("Personal");
        try {
            //Llenar tabla de registrados
            String sql = "SELECT * FROM personal";
            Statement s = Conexion.obtener().createStatement();
            ResultSet rs = s.executeQuery(sql);
            DefaultTableModel model = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Documento"}, 0);
            while(rs.next())
            {
                String d = rs.getString("PerCod");
                String e = rs.getString("PerTraNom");
                String f = rs.getString("PerDocNum");
                model.addRow(new Object[]{d, e, f });
            }
            personal.jTable2.setModel(model);
        } catch (SQLException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(TipoDocumento.class.getName()).log(Level.SEVERE, null, ex);
        }
        personal.comboBox_tipoDocumento();
        personal.comboBox_EstadoCivil();
        personal.comboBox_GrupoSanguineo();
        personal.comboBox_Regimen();
        personal.comboBox_Sexo();
        personal.comboBox_SituacionEPS();
        personal.comboBox_banco();
        personal.comboBox_nivelEducativoDes();
        personal.comboBox_ocupacion();
        personal.comboBox_pais();
        personal.comboBox_ubigeo();
        personal.comboBox_Sino();
        personal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anio;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox<String> comboBox_ControlInmediato;
    private javax.swing.JComboBox<String> comboBox_Discapacidad;
    private javax.swing.JComboBox<String> comboBox_EstadoCivil;
    private javax.swing.JComboBox<String> comboBox_GrupoSanguineo;
    private javax.swing.JComboBox<String> comboBox_Regimen;
    private javax.swing.JComboBox<String> comboBox_Seguro;
    private javax.swing.JComboBox<String> comboBox_Sexo;
    private javax.swing.JComboBox<String> comboBox_Sindicalizado;
    private javax.swing.JComboBox<String> comboBox_SituacionEPS;
    private javax.swing.JComboBox<String> comboBox_banco;
    private javax.swing.JComboBox<String> comboBox_nivelEducativoDes;
    private javax.swing.JComboBox<String> comboBox_ocupacion;
    private javax.swing.JComboBox<String> comboBox_pais;
    private javax.swing.JComboBox<String> comboBox_tipoDocumento;
    private javax.swing.JComboBox<String> comboBox_ubigeo;
    private javax.swing.JTextField correo;
    private javax.swing.JSpinner dia;
    private javax.swing.JTextField documento;
    private javax.swing.JTextField domicilio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField materno;
    private javax.swing.JTextField maternoConyuge;
    private javax.swing.JSpinner mes;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreConyuge;
    private javax.swing.JTextField numeroCuenta;
    private javax.swing.JSpinner numeroHijos;
    private javax.swing.JTextField otrosIngresos;
    private javax.swing.JTextField paterno;
    private javax.swing.JTextField paternoConyuge;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

}
